_wandb:
    value:
        cli_version: 0.22.2
        e:
            2x9j6cbso6svimzcbqqpjtyljzf74tif:
                codePath: ControllingBehavioralDiversity/het_control/run_scripts/attempt2.ipynb
                codePathLocal: attempt2.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "105089261568"
                        used: "63772946432"
                executable: /home/grad/doc/2027/spatel2/miniconda3/envs/ad2c/bin/python
                git:
                    commit: c16388708bcab43ca70087f746e0072afcbccfe0
                    remote: https://github.com/Svar7769/AD2C.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-333b89b8-fd88-291c-adfa-06d07ef25a61
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-790be8a1-ce9e-7a39-92fa-78e52cccfa43
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-89a20cf1-6e87-9dd7-be69-c3c3d5079f3d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-fe1a3067-ead8-2486-73c3-d526f581ec9d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-0ce1441e-8524-10b1-ea99-5e832f41928d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-02a4c89e-bcab-07fd-0e3c-f5bc433b4f1d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-47552d1d-fc25-7863-c501-dbed79f5f4e8
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-2828cff5-4f2a-c75f-8885-8e8e87bc45b6
                host: cs-gpu1.cs.uml.edu
                memory:
                    total: "1081825751040"
                os: Linux-6.8.0-64-generic-x86_64-with-glibc2.39
                program: /home/grad/doc/2027/spatel2/AD2C_testBed/AD2C/ControllingBehavioralDiversity/het_control/run_scripts/attempt2.ipynb
                python: CPython 3.9.23
                root: /home/grad/doc/2027/spatel2/AD2C_testBed/AD2C/ControllingBehavioralDiversity/het_control/run_scripts
                startedAt: "2025-11-26T23:35:05.998503Z"
                writerId: 2x9j6cbso6svimzcbqqpjtyljzf74tif
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 13
                - 14
            "4": 3.9.23
            "5": 0.22.2
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
